# 端口
server:
    port: 8082

spring:
    main:
        allow-bean-definition-overriding: true

    # redis 配置
    redis:
        shiro:
            # Shiro Redis 服务器地址
            # Redis服务器地址
            host: 127.0.0.1:6379
            # Redis服务器连接密码（默认为空）
            password:
            # Redis数据库索引（默认为0）
            database: 2
            # 连接超时时间
            timeout: 1800
        
        
        
        
        